name: Android CI/CD with GitHub Releases

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build_and_test:
    name: Build, Lint & Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  build_release:
    name: Build Release AAB & Create GitHub Release
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Decode Keystore
        env:
          KEYSTORE_BASE64_SECRET: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo $KEYSTORE_BASE64_SECRET | base64 --decode > ${{ github.workspace }}/release.keystore

      - name: Build Release AAB (Signed)
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          ./gradlew bundleRelease \
            -Pandroid.injected.signing.store.file=${{ github.workspace }}/release.keystore \
            -Pandroid.injected.signing.store.password=$SIGNING_STORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$SIGNING_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$SIGNING_KEY_PASSWORD

      # KHÔNG CÓ UPLOAD ARTIFACT RIÊNG NỮA VÌ SẼ UPLOAD LÊN RELEASE
      # - name: Upload Release AAB Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: app-release.aab
      #     path: app/build/outputs/bundle/release/app-release.aab

      # ĐÂY LÀ CHỖ SỬA: `steps:` con của `build_release` thì `- name:` phải cùng cấp
      - name: Create GitHub Release
        id: create_release # Đặt ID để có thể tham chiếu output
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token này được GitHub Actions cung cấp tự động
        with:
          tag_name: v${{ github.run_number }} # Tạo tag dựa trên số lần chạy workflow (ví dụ: v1, v2, v3)
                                            # Hoặc bạn có thể dùng tag từ commit: ${{ github.ref_name }} nếu bạn push tag
          release_name: Release v${{ github.run_number }}
          body: | # Nội dung mô tả cho release, bạn có thể thêm chi tiết hơn
            New release based on commit ${{ github.sha }}
            Triggered by push to branch: ${{ github.ref_name }}
          draft: false # false: publish ngay, true: tạo bản nháp
          prerelease: false # false: release chính thức, true: bản pre-release

      - name: Upload AAB to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # Lấy URL upload từ bước tạo release
          asset_path: ./app/build/outputs/bundle/release/app-release.aab # Đường dẫn tới file AAB
                                                                       # (Kiểm tra lại đường dẫn này trong dự án của bạn)
          asset_name: app-release-v${{ github.run_number }}.aab # Tên file trên Release
          asset_content_type: application/vnd.android.package-archive